jobs:
  verify:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Get Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./check/action

name: Test

on:
  schedule:
    - cron: "45 1/3 * * *"
